---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    # Test we can logon to 'webservers' and execute python with json lib.
    # ansible webservers -m ping

    - name: Example from an Ansible Playbook
      ansible.builtin.ping:
